services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
